version: '2'
services:
  homeless-service:
    build: .
    image: "${DOCKER_IMAGE}"
    environment:
    - CONFIG_BUCKET=${CONFIG_BUCKET}  
    - DEPLOY_TARGET=${DEPLOY_TARGET}
    - PROJ_SETTINGS_DIR=${PROJ_SETTINGS_DIR}
    command: /code/docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
