# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelessApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicHomelessness',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chronichomelessnesstype', models.CharField(max_length=255)),
                ('sheltertype', models.CharField(max_length=255)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chronichomelessness',
            },
        ),
        migrations.CreateModel(
            name='DomesticViolence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sheltertype', models.CharField(max_length=255)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'domesticviolence',
            },
        ),
        migrations.CreateModel(
            name='LengthOfHomelessness',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lengthofhomelessnesstype', models.CharField(max_length=255)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lengthofhomelessness',
            },
        ),
        migrations.CreateModel(
            name='SleepingLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sleepinglocation', models.CharField(max_length=255)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sleepinglocation',
            },
        ),
        migrations.AlterField(
            model_name='agehousecomposition',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='disability',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gender',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='geographiclocation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='homelessindividuals',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='veterans',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
