# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homelessApp', '0004_acsage_acsdisability_acsrace_acsveteran'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agehousecomposition',
            options={'verbose_name_plural': 'Age House Composition'},
        ),
        migrations.AlterModelOptions(
            name='chronichomelessness',
            options={'verbose_name_plural': 'Chronic Homelessness'},
        ),
        migrations.AlterModelOptions(
            name='disability',
            options={'verbose_name_plural': 'Disability'},
        ),
        migrations.AlterModelOptions(
            name='domesticviolence',
            options={'verbose_name_plural': 'Domestic Violence'},
        ),
        migrations.AlterModelOptions(
            name='ethnicity',
            options={'verbose_name_plural': 'Ethnicity'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name_plural': 'Gender'},
        ),
        migrations.AlterModelOptions(
            name='geographiclocation',
            options={'verbose_name_plural': 'Geographic Location'},
        ),
        migrations.AlterModelOptions(
            name='homelessindividuals',
            options={'verbose_name_plural': 'Homeless Individuals'},
        ),
        migrations.AlterModelOptions(
            name='lengthofhomelessness',
            options={'verbose_name_plural': 'Length of Homelessness'},
        ),
        migrations.AlterModelOptions(
            name='sleepinglocation',
            options={'verbose_name_plural': 'Sleeping Location'},
        ),
        migrations.AlterModelOptions(
            name='veterans',
            options={'verbose_name_plural': 'Veterans'},
        ),
    ]
