# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelessApp', '0005_auto_20170316_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitacscomp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=255)),
                ('pit_percent', models.FloatField()),
                ('acs_percent', models.FloatField()),
            ],
            options={
                'db_table': 'pitacscomp',
            },
        ),
        migrations.CreateModel(
            name='Pitacsethcomp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity', models.CharField(max_length=255)),
                ('hud_homeless', models.FloatField(blank=True, null=True)),
                ('mult_poverty_homeless', models.FloatField(blank=True, null=True)),
                ('mult_general_homeless', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pitacsethcomp',
            },
        ),
        migrations.RemoveField(
            model_name='acsage',
            name='sex',
        ),
    ]
