# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homelessApp', '0006_auto_20170324_0247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitacsethcomp',
            old_name='mult_general_homeless',
            new_name='mult_general',
        ),
    ]
