# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 17:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelessApp', '0008_auto_20170324_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinnedAge211',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('freq', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'binned_age_211',
            },
        ),
        migrations.CreateModel(
            name='Gender211',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('freq', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gender_211',
            },
        ),
        migrations.CreateModel(
            name='Military211',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('freq', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'military_211',
            },
        ),
        migrations.CreateModel(
            name='MonthDemand211',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('freq', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'month_demand_211',
            },
        ),
        migrations.CreateModel(
            name='Service211',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('freq', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_211',
            },
        ),
    ]
